name: flutter_rust_bridge_example
description: flutter rust bridge example
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  meta: ^1.3.0
  lints: ^1.0.1
  flutter_rust_bridge:
    path: ../../../frb_dart
  test: ^1.18.2
  vm_service: ^7.3.0
  freezed_annotation: ^1.1.0
dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.0
