name: flutter_rust_bridge_example
description: flutter rust bridge example
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  meta: ^1.8.0
  lints: ^2.0.1
  flutter_rust_bridge:
    path: ../../../frb_dart
  vm_service: ^9.0.0
  freezed_annotation: ^2.2.0
  ffi: ^2.0.1
  js: ^0.6.5
  test_core: ^0.4.16
  test: ^1.21.4
  uuid: ^3.0.6
  collection: ^1.16.0 
dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  ffigen: ^7.2.6
