name: flutter_rust_bridge_example
description: flutter rust bridge example
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  meta: ^1.8.0
  lints: ^2.0.0
  flutter_rust_bridge:
    path: ../../../frb_dart
  test: ^1.21.4
  vm_service: ^9.0.0
  freezed_annotation: ^2.1.0
  ffi: ^2.0.1
dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  ffigen: ^6.1.2
