[book]
authors = ["authors of flutter_rust_bridge, see GitHub README.md for detailed contributions"]
language = "en"
src = "src"
title = "flutter_rust_bridge"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
