name: frb_example_gallery
description: flutter rust bridge example
version: 1.0.0
publish_to: none
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  lints: ^5.1.1
  rust_builder:
    path: rust_builder
  flutter_rust_bridge:
    path: ../../frb_dart
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
dev_dependencies:
  test: ^1.21.4
  freezed: ^3.0.6
  build_runner: ^2.4.4
  ffigen: ^16.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
