name: flutter_rust_bridge_utils
description: Utility for flutter_rust_bridge, may publish later
version: 1.0.0
repository: https://github.com/fzyzcjy/flutter_rust_bridge
environment:
  sdk: ">=3.0.0 <4.0.0"
publish_to: none

dependencies:
  args: ^2.1.1
  build_cli_annotations: ^2.1.0
  glob: ^2.1.2
  recase: ^4.0.0
  puppeteer: ^3.1.1
  shelf: ^1.3.2
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.2
  web_socket_channel: ^2.2.0
  flutter_rust_bridge:
    path: ../frb_dart
  native_assets_cli: ^0.2.0
  js: ^0.6.4
  test_core: ^0.5.9
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.2.0
  build_cli: ^2.2.0
  flutter_lints: ^3.0.1
  test: ^1.24.0
