name: flutter_rust_bridge
description: High-level memory-safe binding generator for Flutter/Dart <-> Rust
version: 2.3.0
repository: https://github.com/fzyzcjy/flutter_rust_bridge
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  args: ^2.3.1
  async: ^2.11.0
  build_cli_annotations: ^2.1.0
  meta: ^1.3.0
  path: ^1.8.1
  web: '>=0.5.0 <2.0.0'
dev_dependencies:
  build_cli: ^2.2.0
  build_runner: ^2.2.0
  ffigen: ^11.0.0
  flutter_lints: ^3.0.1
  test: ^1.16.8
  mocktail: ^1.0.1
