name: flutter_rust_bridge
description: High-level memory-safe binding generator for Flutter/Dart <-> Rust
version: 1.37.2
repository: https://github.com/fzyzcjy/flutter_rust_bridge
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  meta: ^1.3.0
dev_dependencies:
  lints: ">=1.0.1 <3.0.0"
  test: ^1.16.8
