on:
  workflow_call:
    inputs:
      flutter_version:
        required: false
        type: string
        default: '3.3.1'
      rust_version:
        required: false
        type: string
        default: '1.64.0'
      image:
        required: true
        type: string
      family:
        required: true
        type: string

jobs:
  codegen:

    runs-on: ${{ inputs.image }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ inputs.rust_version }}
          override: true
          components: rustfmt, clippy

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ inputs.flutter_version }}
          architecture: x64
      

      # needed by `ffigen`, see https://github.com/dart-lang/ffigen#installing-llvm
      - name: Install llvm dependency (Linux)
        if: ${{ inputs.family == 'linux' }}
        run: sudo apt update && sudo apt-get install -y libclang-dev

      - name: Install dart dependencies (single block)
        working-directory: ./frb_example/pure_dart/dart
        run: dart pub get

      - name: Install dart dependencies (multi blocks)
        working-directory: ./frb_example/pure_dart_multi/dart
        run: dart pub get

      - name: Install Flutter dependencies
        working-directory: ./frb_example/with_flutter
        run: flutter pub get

      # NOTE in windows, need "\\" instead of "/"
      - name: Run codegen to pure_dart example (non-windows)
        if: ${{ inputs.family != 'windows' }}
        working-directory: ./frb_codegen
        run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen --features "chrono,uuid" --
          --rust-input ../frb_example/pure_dart/rust/src/api.rs
          --dart-output ../frb_example/pure_dart/dart/lib/bridge_generated.dart
          --dart-decl-output ../frb_example/pure_dart/dart/lib/bridge_definitions.dart
          --dart-format-line-length 120
          --wasm
        env:
          RUST_LOG: debug

      - name: Run codegen to pure_dart example (windows)
        if: ${{ inputs.family == 'windows' }}
        working-directory: ./frb_codegen
        run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen --features "chrono,uuid" --
          --rust-input ..\\frb_example\\pure_dart\\rust\\src\\api.rs
          --dart-output ..\\frb_example\\pure_dart\\dart\\lib\\bridge_generated.dart
          --dart-decl-output ..\\frb_example\\pure_dart\\dart\\lib\\bridge_definitions.dart
          --dart-format-line-length 120
          --wasm
        env:
          RUST_LOG: debug

      # NOTE in windows, need "\\" instead of "/"
      - name: Run codegen to pure_dart_multi example (non-windows)
        if: ${{ inputs.family != 'windows' }}
        working-directory: ./frb_codegen
        run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen --
          --rust-input ../frb_example/pure_dart_multi/rust/src/api_1.rs ../frb_example/pure_dart_multi/rust/src/api_2.rs
          --dart-output ../frb_example/pure_dart_multi/dart/lib/bridge_generated_api_1.dart ../frb_example/pure_dart_multi/dart/lib/bridge_generated_api_2.dart
          --dart-format-line-length 120
          --rust-output ../frb_example/pure_dart_multi/rust/src/generated_api_1.rs ../frb_example/pure_dart_multi/rust/src/generated_api_2.rs
          --class-name ApiClass1 ApiClass2
        env:
          RUST_LOG: debug
      - name: Run codegen to pure_dart_multi example (windows)
        if: ${{ inputs.family == 'windows' }}
        working-directory: ./frb_codegen
        run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen --
          --rust-input ..\\frb_example\\pure_dart_multi\\rust\\src\\api_1.rs ..\\frb_example\\pure_dart_multi\\rust\\src\\api_2.rs
          --dart-output ..\\frb_example\\pure_dart_multi\\dart\\lib\\bridge_generated_api_1.dart ..\\frb_example\\pure_dart_multi\\dart\\lib\\bridge_generated_api_2.dart
          --dart-format-line-length 120
          --rust-output ..\\frb_example\\pure_dart_multi\\rust\\src\\generated_api_1.rs ..\\frb_example\\pure_dart_multi\\rust\\src\\generated_api_2.rs
          --class-name ApiClass1 ApiClass2
        env:
            RUST_LOG: debug

      - name: Run codegen to with_flutter example (non-windows)
        if: ${{ inputs.family != 'windows' }}
        working-directory: ./frb_codegen
        run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen --
          --rust-input ../frb_example/with_flutter/rust/src/api.rs
          --dart-output ../frb_example/with_flutter/lib/bridge_generated.dart
          --c-output ../frb_example/with_flutter/ios/Runner/bridge_generated.h
          --dart-decl-output ../frb_example/with_flutter/lib/bridge_definitions.dart
          --dart-format-line-length 120
          --wasm
        env:
          RUST_LOG: debug
      - name: Run codegen to with_flutter example (windows)
        if: ${{ inputs.family == 'windows' }}
        working-directory: ./frb_codegen
        run: cargo run --package flutter_rust_bridge_codegen --bin flutter_rust_bridge_codegen --
          --rust-input ..\\frb_example\\with_flutter\\rust\\src\\api.rs
          --dart-output ..\\frb_example\\with_flutter\\lib\\bridge_generated.dart
          --c-output ..\\frb_example\\with_flutter\\ios\\Runner\\bridge_generated.h
          --dart-decl-output ..\\frb_example\\with_flutter\\lib\\bridge_definitions.dart
          --dart-format-line-length 120
          --wasm
        env:
          RUST_LOG: debug

      # #467
      - name: "Modify cross-platform code (windows) (single block)"
        if: ${{ inputs.family == 'windows' }}
        run: sed -i -e 's/^typedef uintptr_t =.*$/typedef uintptr_t = ffi.UnsignedLong;/g' frb_example/pure_dart/dart/lib/bridge_generated.io.dart

      - name: Generate codegen help
        working-directory: ./frb_codegen
        # The file extension is different on Windows.
        if: ${{ inputs.family != 'windows' }}
        run: cargo run -- --help > ../book/src/help.txt

      - name: Generate server help
        working-directory: ./frb_dart
        run: dart pub get && dart run bin/serve.dart --help > ../book/src/help.serve.txt

      - name: "Check no code change
          (If fail: Please ensure you have run codegen on examples and commit those changes!
          On Windows, see https://github.com/fzyzcjy/flutter_rust_bridge/pull/536#issuecomment-1170259918
          for additional instructions.)
          If you have installed `just`, use `just precommit`."
        run: git diff --exit-code
