name: Publish

on:
  workflow_dispatch: {}

jobs:
  rust_codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          path: './frb_codegen'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  rust_runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          path: './frb_rust'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  dart_runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_CREDENTIALS_JSON }}
          flutter_package: false
          skip_test: true
